=== Asdamos/University/2015-2016/Zima/Projekt zespołowy/kebab-explorer/Anzen/src/main/resources/jsonSchemes/commentUpdateSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Comment Add Schema",
  "type": "object",
  "properties": {

    "_id" : {
      "type" : "number"
    },

    "text" : {
      "type" : "string"
    },
    "restaurant" : {
      "type" : "string"
    },
    "author" : {
      "type" : "string"
    },
    "rating" : {
      "type": "integer",
      "minimum": 1,
      "maximum" : 5
    }
  },
  "required": [
    "text",
    "restaurant",
    "author",
    "rating"
  ]
}

=== Asdamos/University/2015-2016/Zima/Projekt zespołowy/kebab-explorer/Anzen/src/test/resources/expected/CommentTest/getAllCommentsTest/bbednarczyk.json
[
  {
    "_id": 1,
    "author": "bbednarczyk",
    "restaurant": "kavos",
    "text": "Nie wiem. Nie bylem.",
    "rating" : 3
  },
  {
    "_id": 2,
    "author": "bbednarczyk",
    "restaurant": "le_gyros",
    "text": "Bardzo slaby kebab. Nie polecam",
    "rating" : 1
  },
  {
    "_id": 3,
    "author": "bbednarczyk",
    "restaurant": "arslan_kebab",
    "text": "Dobra kuchnia. Wykwintny kebab. Polecam.",
    "rating" : 5
  }
]

=== Asdamos/University/2015-2016/Zima/Projekt zespołowy/kebab-explorer/Anzen/src/test/resources/expected/CommentTest/getAllCommentsTest/allComments.json
[
  {
    "_id": 1,
    "author": "bbednarczyk",
    "restaurant": "kavos",
    "text": "Nie wiem. Nie bylem.",
    "rating" : 3
  },
  {
    "_id": 2,
    "author": "bbednarczyk",
    "restaurant": "le_gyros",
    "text": "Bardzo slaby kebab. Nie polecam",
    "rating" : 1
  },
  {
    "_id": 3,
    "author": "bbednarczyk",
    "restaurant": "arslan_kebab",
    "text": "Dobra kuchnia. Wykwintny kebab. Polecam.",
    "rating" : 5
  },
  {
    "_id": 4,
    "author": "MrTurek",
    "restaurant": "arslan_kebab",
    "text": "Good Kebab.",
    "rating" : 4
  },
  {
    "_id": 5,
    "author": "MrTurek",
    "restaurant": "kebab_hut",
    "text": "Le kabab est terrible.",
    "rating" : 2
  }
]
