=== Asdamos/University/2015-2016/Zima/Projekt zespołowy/kebab-explorer/Anzen/src/main/resources/jsonSchemes/restaurantAddSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Restaurant Add Schema",
  "type": "object",
  "properties": {
    "address": {
      "type": "object",
      "properties": {
        "city": {
          "type": "string",
          "pattern": "Wroc≈Çaw"
        },
        "postcode": {
          "type": "string",
          "pattern": "[0-9]{2}-[0-9]{3}"
        },
        "street": {
          "type": "string"
        }
      },
      "required": [
        "city",
        "postcode",
        "street"
      ]
    },
    "email": {
      "type": "string",
      "format": "email"
    },
    "location": {
      "type": "object"
    },
    "menu": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "dishName": {
            "type": "string"
          },
          "dishPrice": {
            "type": "number",
            "minimum": 0,
            "exclusiveMinimum": true
          },
          "description": {
            "type": "string"
          }
        },
        "required": [
          "dishName",
          "dishPrice"
        ]
      }
    },
    "fullname": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "phone": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "[0-9]{3} [0-9]{3} [0-9]{3}"
      }
    }
  },
  "required": [
    "address",
    "location",
    "name"
  ]
}

=== Asdamos/University/2015-2016/Zima/Projekt zespołowy/kebab-explorer/Anzen/src/test/resources/expected/RestaurantTest/addRestaurantTest/kebab_king.json
{
  "address": {
    "city": "Wroc≈Çaw",
    "postcode": "50-068",
    "street": "Swidnicka 24/26"
  },
  "fullname": "Kebab King",
  "location": {
    "type": "Point",
    "coordinates": [
      51.1065599,
      17.032065
    ]
  },

  "menu": [
    {
      "dishName": "Talerz kebab z kurczaka",
      "dishPrice": 22.0
    },
    {
      "dishName": "Talerz kebab mieszany",
      "dishPrice": 22.0
    }
  ],
  "name": "kebab_king",
  "phone": [
    "223 163 737"
  ]
}
